version: '3'
services:
  fsdemo-frontend:
    image:   registry.cn-hangzhou.aliyuncs.com/xdorg1/fsdemo-frontend:latest
    ports:
      - "8080:80"
    volumes:
      - "./entrypoint.sh:/entrypoint.sh"
    command: /entrypoint.sh -d fsdemo-usercenter:8081,transactionagentservice:8082 -c "nginx -g 'daemon off;'"
  fsdemo-usercenter:
    image: registry.cn-hangzhou.aliyuncs.com/xdorg1/fsdemo-usercenter
    ports:
      - "8081:8081"
    environment:
      DEBUG_MODE: "true"
      SERVERPORT: "8081"
      JDBCURL: "usercenter?setUnicode=true&characterEncoding=utf8"
      DBUSERNAME: "xiaodong"
      DBPASSWORD: "time4@FUN"
      DBSERVER: "mysqldb"
      DBPORT: "3306"
    volumes:
      - "./entrypoint.sh:/entrypoint.sh"
    command: "/entrypoint.sh -d mysqldb:3306 -c ./run.sh;"
  transactionagentservice:
    image: registry.cn-hangzhou.aliyuncs.com/xdorg1/transactionagentservice
    ports:
      - "8082:8082"
    environment:
      DEBUG_MODE: "true"
      SERVERPORT: "8082"
      JDBCURL: "transproddb?setUnicode=true&characterEncoding=utf8"
      DBUSERNAME: "xiaodong"
      DBPASSWORD: "time4@FUN"
      DBSERVER: "mysqldb"
      DBPORT: "3306"
    volumes:
      - "./entrypoint.sh:/entrypoint.sh"
    command: "/entrypoint.sh -d mysqldb:3306 -c ./run.sh"
  fsdemo-priceservice:
    image: registry.cn-hangzhou.aliyuncs.com/xdorg1/fsdemo-priceservice
    ports:
      - "8083:8083"
    volumes:
      - "./entrypoint.sh:/entrypoint.sh"
    command: "/entrypoint.sh -d mysqldb:3306 -c fsdemo-priceservice"
  mysqldb:
    image: mysql:8.0.19
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "time4@FUN"
      MYSQL_USER: 'xiaodong'
      MYSQL_PASS: 'time4@FUN'
    restart: always
    volumes:
      - "./init:/docker-entrypoint-initdb.d/"
#      - "./db:/var/lib/mysql"
#      - "./conf/my.cnf:/etc/my.cnf"




