apiVersion: v1
kind: Service
metadata:
  name: nginx-nfs
  labels:
    app: nginx-nfs
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30180
  selector:
    app: nginx-nfs-selector
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-nfs-deployment
spec:
  selector:
    matchLabels:
      app: nginx-nfs-selector
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-nfs-selector
    spec:
      containers:
        - name: nginx-nfs
          image: nginx:1.7.9
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nfs
              mountPath: /usr/share/nginx/html

      volumes:
        - name: nfs
          persistentVolumeClaim:
            claimName: mysql-pvc