apiVersion: apps/v1
kind: Deployment
metadata:
  name: fsdemo-emplyservice
  labels:
    app: fsdemo-emplyservice
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fsdemo-emplyservice
  template:
    metadata:
      labels:
        app: fsdemo-emplyservice
        version: v1
    spec:
      initContainers:
        - name: fsdemo-emplyservice-init
          image: busybox
          imagePullPolicy: IfNotPresent
          env:
            - name: DBSERVER
              value: "xdpostgres"
            - name: DBPORT
              value: "5432"
          command: ['sh', '-c']
          args:
          - echo Prepare to apollo initialize..;
            until nc -w 1 -z $DBSERVER $DBPORT;
            do echo EMPLYSERVICE Waiting for database initialization to complete..; sleep 5; done;
            echo database is ready.;
      containers:
        - name: fsdemo-emplyservice
          image: xdt440subuntuharbor.xdli.com/xdorg1/fsdemo-emplyservice
          imagePullPolicy: Always
          env:
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: "http://skywalking-skywalking-helm-oap:11800"
          ports:
            - containerPort: 8086
          resources: {}
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: fsdemo-emplyservice
  labels:
    app: fsdemo-emplyservice
    service: fsdemo-emplyservice
spec:
#  type: NodePort
  selector:
    app: fsdemo-emplyservice
  ports:
    - port: 8086
      name: http

