apiVersion: apps/v1
kind: Deployment
metadata:
  name: fsdemo-articlenodejs
  labels:
    app: fsdemo-articlenodejs
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fsdemo-articlenodejs
  template:
    metadata:
      labels:
        app: fsdemo-articlenodejs
        version: v1
    spec:
      initContainers:
        - name: fsdemo-articlenodejs-init
          image: busybox
          imagePullPolicy: IfNotPresent
          env:
            - name: DBSERVER
              value: "xdpostgres"
            - name: DBPORT
              value: "5432"
          command: ['sh', '-c']
          args:
          - echo Prepare to apollo initialize..;
            until nc -w 1 -z $DBSERVER $DBPORT;
            do echo ARTICLENODEJS Waiting for database initialization to complete..; sleep 5; done;
            echo database is ready.;
      containers:
        - name: fsdemo-articlenodejs
          image: xdt440subuntuharbor.xdli.com/xdorg1/fsdemo-articlenodejs
          imagePullPolicy: Always
          env:
            - name: SW_AGENT_NAME
              value: "fsdemo-articlenodejs"
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              value: "skywalking-skywalking-helm-oap:11800"
          ports:
            - containerPort: 8087
          resources: {}
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: fsdemo-articlenodejs
  labels:
    app: fsdemo-articlenodejs
    service: fsdemo-articlenodejs
spec:
  type: NodePort
  selector:
    app: fsdemo-articlenodejs
  ports:
    - port: 8087
      name: http
      targetPort: 8087
      nodePort: 31582

