apiVersion: apps/v1
kind: Deployment
metadata:
  name: fsdemo-usercenter
  labels:
    app: fsdemo-usercenter
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fsdemo-usercenter
  template:
    metadata:
      annotations:
        agent.skywalking.apache.org/agent.service_name: "fsdemo-usercenter"
      labels:
        swck-java-agent-injected: "true"
        app: fsdemo-usercenter
        version: v1
    spec:
      initContainers:
        - name: fsdemo-usercenter-init
          image: busybox
          imagePullPolicy: IfNotPresent
          env:
            - name: DBSERVER
              value: "mysqldb"
            - name: DBPORT
              value: "3306"
          command: ['sh', '-c']
          args:
          - echo Prepare to apollo initialize..;
            until nc -w 1 -z $DBSERVER $DBPORT;
            do echo USERCENTER Waiting for database initialization to complete..; sleep 5; done;
            echo database is ready.;
      containers:
        - name: fsdemo-usercenter
          image: xdt440subuntuharbor.xdli.com/xdorg1/fsdemo-usercenter
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          resources: {}
          env:
            - name: SERVERPORT
              value: "8081"
            - name: DEBUG_MODE
              value: "true"
            - name: JDBCURL
              value: "usercenter?setUnicode=true&characterEncoding=utf8"
            - name: DBUSERNAME
              value: "xiaodong"
            - name: DBPASSWORD
              value: "time4@FUN"
            - name: DBSERVER
              value: "mysqldb"
            - name: DBPORT
              value: "3306"
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: fsdemo-usercenter
  labels:
    app: fsdemo-usercenter
    service: fsdemo-usercenter
spec:
#  type: NodePort
  selector:
    app: fsdemo-usercenter
  ports:
    - port: 8081
      name: http

