server:
  port: 8081
spring:
#  datasource:
#    url: jdbc:mysql://mysqldb:3306/usercenter?setUnicode=true&characterEncoding=utf8
#    username: xiaodong
#    password: time4@FUN
#    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
debug: true
fsdemo:
  fsdemo-gateway: fsdemo-spcgtw:8060 # should use fsdemo-gateway.fsdemo.com in k8s env.
#  fsdemo-gateway: fsdemo-frontend:8080 # should use fsdemo-gateway.fsdemo.com in k8s env.
  oauth:
    client_id_fsdemo_frontend: fsdemo-frontend
    client_id_fsdemoapp: fsdemoapp
    client_credential: time4@FUN
    tokenurl: http://fsdemo-authsrv:8084/oauth/token
    grant_type_code: authorization_code
    redirect_uri: http://fsdemo-usercenter:8081/usercenter/auth
