apiVersion: apps/v1
kind: Deployment
metadata:
  name: fsdemo-usercenter
  labels:
    app: fsdemo-usercenter
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fsdemo-usercenter
  template:
    metadata:
      labels:
        app: fsdemo-usercenter
        version: v1
    spec:
      volumes:
        - name: skywalking-agent
          emptyDir: { }
      initContainers:
        - name: fsdemo-usercenter-init
          image: busybox
          imagePullPolicy: IfNotPresent
          env:
            - name: DBSERVER
              value: "mysqldb"
            - name: DBPORT
              value: "3306"
          command: ['sh', '-c']
          args:
          - echo Prepare to apollo initialize..;
            until nc -w 1 -z $DBSERVER $DBPORT;
            do echo USERCENTER Waiting for database initialization to complete..; sleep 5; done;
            echo database is ready.;
        - name: agent-container
          image: apache/skywalking-java-agent:8.14.0-java8
          volumeMounts:
            - name: skywalking-agent
              mountPath: /agent
          command: [ "/bin/sh" ]
          args: [ "-c", "cp -R /skywalking/agent /agent/" ]
      containers:
        - name: fsdemo-usercenter
          image: registry.cn-hangzhou.aliyuncs.com/xdorg1/fsdemo-usercenter
          imagePullPolicy: Always
          volumeMounts:
            - name: skywalking-agent
              mountPath: /skywalking
          ports:
            - containerPort: 8081
          resources: {}
          env:
            - name: SERVERPORT
              value: "8081"
            - name: DEBUG_MODE
              value: "true"
            - name: JDBCURL
              value: "usercenter?setUnicode=true&characterEncoding=utf8"
            - name: DBUSERNAME
              value: "xiaodong"
            - name: DBPASSWORD
              value: "time4@FUN"
            - name: DBSERVER
              value: "mysqldb"
            - name: DBPORT
              value: "3306"
            - name: JAVA_TOOL_OPTIONS
              value: "-javaagent:/skywalking/agent/skywalking-agent.jar"
            - name: SW_AGENT_NAME
              value: fsdemo-usercenter
            - name: SW_AGENT_COLLECTOR_BACKEND_SERVICES
              # FQDN: servicename.namespacename.svc.cluster.local
              value: skywalking-oap:11800
      restartPolicy: Always


---

apiVersion: v1
kind: Service
metadata:
  name: fsdemo-usercenter
  labels:
    app: fsdemo-usercenter
    service: fsdemo-usercenter
spec:
#  type: NodePort
  selector:
    app: fsdemo-usercenter
  ports:
    - port: 8081
      name: http

