kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-pvc-istio
  namespace: fsdemo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs